<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>New Order Notification</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,sans-serif;">

    <div style="max-width:700px;margin:20px auto;background:#ffffff;padding:30px;border-radius:8px;">

        <h2 style="color:#dc3545;margin-top:0;">
            🛒 New Order Received
        </h2>

        <p>
            A new order has been placed on your website and requires processing.
        </p>

        <hr>

        <h3>Order Information</h3>

        <table style="width:100%;border-collapse:collapse;">
            <tr>
                <td style="padding:8px 0;"><strong>Order ID</strong></td>
                <td>#{{ $order->id }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Customer Name</strong></td>
                <td>{{ $order->name }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Email</strong></td>
                <td>{{ $order->email }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Phone</strong></td>
                <td>{{ $order->phone }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Address</strong></td>
                <td>{{ $order->address }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Total Amount</strong></td>
                <td>₹{{ number_format($order->total, 2) }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Payment Method</strong></td>
                <td>{{ $order->payment_method }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Payment Status</strong></td>
                <td>{{ $order->payment_status }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Order Status</strong></td>
                <td>{{ ucfirst($order->status) }}</td>
            </tr>
            <tr>
                <td style="padding:8px 0;"><strong>Order Date</strong></td>
                <td>{{ $order->created_at->format('d M Y h:i A') }}</td>
            </tr>
        </table>
        <hr>
        <p>
            Please log in to the admin panel and process this order.
        </p>
        <p>
            Thank you,<br>
            <strong>{{ config('app.name') }}</strong>
        </p>
        <hr>
        <p style="font-size:12px;color:#888;">
            This is an automated notification generated by {{ config('app.name') }}.
        </p>
    </div>
</body>
</html>